# Generated by Django 3.0.8 on 2020-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'shipping'), ('billing', 'billing')], max_length=120),
        ),
    ]
