# Generated by Django 3.0.8 on 2020-08-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='Email',
            new_name='email',
        ),
    ]
