# Generated by Django 3.0.8 on 2020-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Gadget', 'Gadget'), ('Phone', 'Phone'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('vehicle', 'vehicle'), ('Home', 'Home')], default='vehicle', max_length=20)),
            ],
        ),
    ]
