# Generated by Django 3.0.8 on 2020-08-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relax_n_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
